import type { Metadata } from "next";
import { Raleway, Edu_NSW_ACT_Cursive } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const eduHand = Edu_NSW_ACT_Cursive({
  variable: "--font-edu-hand",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${eduHand.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
